ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black
      args: [--safe, --quiet]
      files: ^src/ns2d/

- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
      args: [--profile=black]
      files: ^src/ns2d/

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      files: ^src/ns2d/
      args: [
        "--max-line-length=88",
        "--exclude=.git,__pycache__,docs/source/conf.py,old,build,dist,venv,.venv",
        "--ignore=E203,E266,E501,W503",
        "--max-complexity=10"
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      language_version: python3.12
      args: [--strict, --ignore-missing-imports]
      files: ^src/ns2d/
      exclude: tests/|docs/

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
    - id: prettier
      types: [markdown]

- repo: local
  hooks:
    - id: nox
      name: nox
      entry: nox
      language: system
      types: [python]
      pass_filenames: false
      files: ^(src/|noxfile.py|requirements.txt)
